const {test}=require('node:test');
const assert=require('node:assert/strict');
const {load}=require('./load.cjs');
const Papa=require('papaparse');Papa.default=Papa;
const {parseSkaterCsv}=load('src/lib/projections/parseSkaterCsv.ts');
const {blendSkaterProjections}=load('src/lib/projections/blendSkaterProjections.ts');
const header='Player,Team,Pos,Age,GP,G,A,PTS,PPP,SOG,HIT,BLK';
const row='Test Player,TBL,C,28,80,20,30,50,10,100,0,10';
const csv=r=>`${header}\n${r}`;
const p={id:'row',name:'Test Player',team:'TBL',positions:['C'],age:28,gp:80,goals:20,assists:30,points:50,ppp:10,sog:100,hits:0,blocks:10};
const source=(id,players,weight=50)=>({id,name:id,weight,players});
test('blank projection is distinguishable from a legitimate zero',async()=>{const [a]=await parseSkaterCsv(csv(row.replace(',100,0,10',',100,,10')));assert.ok(a.missingFields.includes('hits'));const [b]=await parseSkaterCsv(csv(row));assert.equal(b.hits,0);assert.ok(!b.missingFields.includes('hits'));});
test('invalid provided projection numbers reject with actionable error',async()=>{await assert.rejects(parseSkaterCsv(csv(row.replace(',100,',',oops,'))),/sog/i);});
test('duplicate rows cannot inflate source count or affect weights',()=>{const actual=blendSkaterProjections([source('a',[p,p]),source('b',[{...p,points:80}])]);assert.equal(actual[0].points,65);assert.equal(actual[0].projectionSources,2);});
test('conflicting identities within one source are excluded from blend',()=>{assert.equal(blendSkaterProjections([source('a',[p,{...p,team:'BOS',points:90}])]).length,0);});
test('CSV conflicting duplicate identity is rejected',async()=>{await assert.rejects(parseSkaterCsv(csv(`${row}\n${row.replace('TBL','BOS')}`)),/duplicate|conflict/i);});
test('missing field renormalizes weights without diluting legitimate zero',()=>{const result=blendSkaterProjections([source('a',[{...p,hits:0,missingFields:['hits']}],80),source('b',[{...p,hits:30}],20)]);assert.equal(result[0].hits,30);const zero=blendSkaterProjections([source('a',[p],80),source('b',[{...p,hits:30}],20)]);assert.equal(zero[0].hits,6);});
test('incomplete projections are withheld from scoring until covered',()=>{assert.equal(blendSkaterProjections([source('a',[{...p,missingFields:['hits']}])]).length,0);});
test('CSV syntax errors are rejected instead of accepting misaligned columns',async()=>{await assert.rejects(parseSkaterCsv(csv(row+',extra')),/CSV|field/i);});
test('identical duplicate CSV rows are rejected with a correction message',async()=>{await assert.rejects(parseSkaterCsv(csv(`${row}\n${row}`)),/duplicate/i);});
test('negative values are invalid but a zero-games projection stays valid',async()=>{await assert.rejects(parseSkaterCsv(csv(row.replace(',100,',',-1,'))),/sog/i);const [zero]=await parseSkaterCsv(csv(row.replace(',80,',',0,')));assert.equal(zero.gp,0);assert.equal(blendSkaterProjections([source('a',[zero])]).length,1);});
test('a player absent from one source uses only available provider weights',()=>{assert.equal(blendSkaterProjections([source('a',[p],10),source('b',[{...p,name:'Other',points:90}],90)]).find(x=>x.name===p.name).points,50);});
test('saved missing-field metadata survives refresh and rejects invalid fields',()=>{const {parseSession,DEFAULT_SESSION}=load('src/lib/session/session.ts');const session={...DEFAULT_SESSION,projectionSources:[{...source('a',[{...p,missingFields:['hits']}]),fileName:'partial.csv'}]};assert.deepEqual(parseSession(JSON.stringify(session)).projectionSources[0].players[0].missingFields,['hits']);session.projectionSources[0].players[0].missingFields=['bogus'];assert.throws(()=>parseSession(JSON.stringify(session)),/saved player/);});
test('a duplicate source ID cannot inflate agreement',()=>{assert.equal(blendSkaterProjections([source('a',[p]),source('a',[p])]).length,0);});
test('diagnostics count distinct rows and expose excluded conflicts and missing input',()=>{const {getProjectionDiagnostics}=load('src/lib/projections/blendSkaterProjections.ts');const d=getProjectionDiagnostics([source('a',[p,p]),source('b',[{...p,missingFields:['hits']}])]);assert.equal(d.sources[0].playerCount,1);assert.ok(d.warnings.some(w=>w.includes('duplicate')));const missing=getProjectionDiagnostics([source('a',[{...p,missingFields:['age']}])]);assert.ok(missing.warnings.some(w=>w.includes('missing age')));});
