const {test}=require('node:test');const assert=require('node:assert/strict');const {load,actions}=require('./load.cjs');
const {blendSkaterProjections}=load('src/lib/projections/blendSkaterProjections.ts');
const p={id:'old-row-1',name:'José Test',team:'TBL',positions:['C'],age:28,gp:80,goals:20,assists:30,points:50,ppp:10,sog:100,hits:0,blocks:10};
const source=(id,players)=>({id,name:id,weight:50,players});
test('projection settings changes preserve real picks',()=>{const picks=[{playerId:'p',pickNumber:15,fantasyTeamId:'team-10'}];const a=actions(picks);a.resetDraftForProjectionChange();assert.deepEqual(a.picks,picks);});
test('projection identity survives single/blended source mode',()=>{const one=blendSkaterProjections([source('a',[p])]);const two=blendSkaterProjections([source('a',[p]),source('b',[{...p,id:'different-row'}])]);assert.equal(one[0].id,two[0].id);});
const {createSessionStore,SESSION_KEY}=load('src/lib/session/session.ts');
const {draftReducer,nextPickNumber,getNextTurn}=load('src/lib/draft/state.ts');
function memory(){const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};}
test('session reload preserves goalies, unknowns and projections',()=>{const db=memory(),store=createSessionStore(db);store.update(s=>({...s,projectionSources:[{...source('a',[p]),fileName:'test.csv'}],draftPicks:[{playerId:'goalie:1',playerName:'Goalie',resolution:'goalie',pickNumber:12,fantasyTeamId:'team-12'}]}));const again=createSessionStore(db).getSnapshot().data;assert.equal(again.draftPicks[0].resolution,'goalie');assert.equal(nextPickNumber(again.draftPicks),13);assert.equal(again.projectionSources[0].players[0].hits,0);});
test('unknown selection correction retains subsequent authoritative positions',()=>{const picks=[{playerId:'unknown:1',pickNumber:1,fantasyTeamId:'team-1'},{playerId:'goalie:2',pickNumber:2,fantasyTeamId:'team-2'}];const corrected=draftReducer(picks,{type:'correct',pick:{...picks[0],playerId:'projected',resolution:'matched'}});assert.equal(corrected[1].pickNumber,2);assert.equal(getNextTurn(corrected,12,3).currentPick,3);});
test('corrupt or newer-version storage is preserved and visibly blocked',()=>{const db=memory();db.setItem(SESSION_KEY,'{"version":99}');const s=createSessionStore(db);assert.ok(s.getSnapshot().warning);s.update(x=>x);assert.equal(db.getItem(SESSION_KEY),'{"version":99}');});
test('stale tab cannot overwrite newer session',()=>{const db=memory(),a=createSessionStore(db),b=createSessionStore(db);a.update(s=>({...s,myDraftSlot:2}));b.update(s=>({...s,myDraftSlot:3}));assert.ok(b.getSnapshot().warning);assert.equal(JSON.parse(db.getItem(SESSION_KEY)).myDraftSlot,2);});
test('quota failure keeps in-memory selection with explicit warning',()=>{const s=createSessionStore({getItem:()=>null,setItem(){throw Error('quota');}});s.update(x=>({...x,myDraftSlot:4}));assert.equal(s.getSnapshot().data.myDraftSlot,4);assert.ok(s.getSnapshot().warning);});
test('unavailable browser storage still permits manual in-memory drafting',()=>{const s=createSessionStore({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}});s.update(x=>({...x,myDraftSlot:5}));assert.equal(s.getSnapshot().data.myDraftSlot,5);assert.ok(s.getSnapshot().warning);});
