const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {parseHTML}=require('linkedom');
const appRoot=process.env.NEVISLY_PATH||path.resolve(__dirname,'../../nevisly');
const {load}=require(appRoot+'/tests/load.cjs');
const {DEFAULT_SESSION,parseSession}=load('src/lib/session/session.ts');
const {bindYahooBridge,receiveYahooV2}=load('src/lib/draft/yahooV2.ts');
const source=n=>fs.readFileSync(path.resolve(__dirname,'..',n),'utf8');
const fixture=fs.readFileSync(__dirname+'/fixtures/history-pick19.html','utf8');
function harness(){
 let bgListener,appReady=false,drop=false,session=structuredClone(DEFAULT_SESSION);const offers=[],frames=[],acks=[],pending=[],storage={},timers=[],tabs={1:{id:1,url:'https://sports-fantasy.media.yahoo.com/draft/hockey/2253754/9'},2:{id:2,url:'http://localhost:3000/'}};
 let destListener,yahooListener;const doc=parseHTML(fixture).document;const callbacks=new Map();
 const window={addEventListener(n,f){callbacks.set(n,f)},dispatchEvent(e){callbacks.get(e.type)?.(e);if(e.type==='nevisly-bridge-v2'&&appReady){const m=JSON.parse(e.detail);if(m.type==='offer')offers.push(m);if(m.type==='observation'){frames.push(m);const r=receiveYahooV2(session,m,[],1000);session=r.session;const ack={type:'ACK_V2',sessionId:session.id,stream:m.stream,sequence:m.sequence,status:r.status};acks.push(ack);request(ack);}}}};
 class CustomEvent{constructor(type,init={}){this.type=type;Object.assign(this,init)}}
 function call(m,tab=2,url=tabs[tab].url){const p=bgListener(m,{tab:tabs[tab],url,frameId:0,documentId:'doc-'+tab,id:'test-extension'});pending.push(p);return p;}
 function request(m){window.dispatchEvent(new CustomEvent('nevisly-bridge-request-v2',{detail:JSON.stringify(m)}));}
 function bootBackground(){vm.runInNewContext(source('background.js'),{URL,crypto:require('node:crypto').webcrypto,Date:class{static now(){return 1000}},console:{warn(){}},browser:{webNavigation:{async getFrame({tabId}){return {documentId:'doc-'+tabId}}},runtime:{id:'test-extension',onMessage:{addListener(f){bgListener=f}}},storage:{local:{async get(){return structuredClone(storage)},async set(x){Object.assign(storage,structuredClone(x))}}},tabs:{async get(id){if(!tabs[id])throw Error('closed');return tabs[id]},async sendMessage(id,m){if(drop&&id===2)throw Error('not ready');if(id===2)destListener(m);if(id===1)yahooListener?.(m);}}}});}
 vm.runInNewContext(source('nevisly.js'),{console,window,CustomEvent,setInterval(f){timers.push(f)},browser:{runtime:{sendMessage:m=>call(m),onMessage:{addListener(f){destListener=f}}}}});
 bootBackground();
 const yc={document:doc,console,MutationObserver:class{observe(){}},setTimeout(){},setInterval(f){timers.push(f)},browser:{runtime:{sendMessage:m=>call(m,1),onMessage:{addListener(f){yahooListener=f}}}}};vm.createContext(yc);vm.runInContext(source('extractor.js'),yc);vm.runInContext(source('yahoo.js'),yc);
 async function flush(){while(pending.length){const batch=pending.splice(0);const r=await Promise.allSettled(batch);for(const x of r)if(x.status==='rejected')throw x.reason;}}
 return {doc,storage,offers,frames,acks,tabs,flush,get session(){return session},setReady(){appReady=true;request({type:'READY_V2',sessionId:session.id,stream:session.bridge?.stream})},connect(){session=bindYahooBridge(session,offers.at(-1));request({type:'BIND_V2',sessionId:session.id,sourceTab:'1',stream:offers.at(-1).stream})},tick(){timers.forEach(f=>f())},drop(v){drop=v},reload(){session=parseSession(JSON.stringify(session));bootBackground();this.setReady()},request(){request({type:'REQUEST_V2',sessionId:session.id})},newDraft(){session={...session,id:'new-local-draft',draftPicks:[],bridge:undefined};this.setReady()},inject:m=>destListener(m),foreign:m=>call(m,2,'https://example.com/'),staleDocument:m=>bgListener(m,{tab:tabs[1],url:tabs[1].url,frameId:0,documentId:'old-document',id:'test-extension'})};
}
test('real scripts recover capture-before-readiness and acknowledge applied history',async()=>{const h=harness();await h.flush();assert.equal(h.session.draftPicks.length,0);h.setReady();await h.flush();h.connect();await h.flush();assert.equal(h.session.draftPicks.length,18);assert.ok(h.acks.some(a=>a.status==='applied'));assert.ok(['applied','replayed'].includes(h.storage['nevisly.bridge.v2'].destinations['2'].lastAck.status));});
test('failed tab delivery recovers through ready replay without a new pick',async()=>{const h=harness();await h.flush();h.setReady();await h.flush();h.drop(true);h.connect();await h.flush();assert.equal(h.session.draftPicks.length,0);h.drop(false);h.setReady();await h.flush();assert.equal(h.session.draftPicks.length,18);});
test('background/page reload preserves stream, sequence and selection identities',async()=>{const h=harness();await h.flush();h.setReady();await h.flush();h.connect();await h.flush();const before=JSON.stringify(h.session.draftPicks),stream=h.session.bridge.stream;h.reload();await h.flush();assert.equal(JSON.stringify(h.session.draftPicks),before);assert.equal(h.session.bridge.stream,stream);assert.equal(h.acks.at(-1).status,'replayed');});
test('old-session frame cannot populate a new local draft',async()=>{const h=harness();await h.flush();h.setReady();await h.flush();h.connect();await h.flush();const old=h.frames.at(-1);h.newDraft();await h.flush();h.inject(old);await h.flush();assert.equal(h.session.draftPicks.length,0);});
test('foreign origin cannot masquerade as the Yahoo sender',async()=>{const h=harness();await h.flush();const before=JSON.stringify(h.storage);await h.foreign({type:'CAPTURE_V2',capture:{rows:[]}});await h.flush();assert.equal(JSON.stringify(h.storage),before);});
test('duplicate unchanged polling preserves sequence while capture freshness advances',async()=>{const h=harness();await h.flush();h.setReady();await h.flush();h.connect();await h.flush();const sequence=h.session.bridge.sequence;h.tick();await h.flush();assert.equal(h.session.bridge.sequence,sequence);assert.equal(h.session.draftPicks.length,18);});
test('DOM header advance alone produces partial coverage and never invents pick 19',async()=>{const h=harness();await h.flush();h.setReady();await h.flush();h.connect();await h.flush();h.doc.querySelector('span').textContent='Round 2, Pick 20';h.tick();await h.flush();assert.equal(h.session.draftPicks.length,18);assert.equal(h.session.bridge.coverage,'partial');});

test('snapshot request reaches the actual Yahoo content script',async()=>{const h=harness();await h.flush();h.setReady();await h.flush();h.connect();await h.flush();const before=h.frames.length;h.request();await h.flush();assert.ok(h.frames.length>before);assert.equal(h.session.draftPicks.length,18);});
test('a delayed message from a replaced Yahoo document is ignored',async()=>{const h=harness();await h.flush();const before=JSON.stringify(h.storage);await h.staleDocument({type:'CAPTURE_V2',capture:{rows:[]}});assert.equal(JSON.stringify(h.storage),before);});
